### ISSUE TITLE
When I try package-extension get error

### ISSUE THREAD

**Issue by xdie** [MoimHossain/azure-repo-folder-extension#1]
error: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Inplace

Thanks advance

**Comment by MoimHossain** [comment]
@xdie : I guess the problem is related to the platform & node version you are using. Azure DevOps extension SDK is not constantly updated (it's a bit out of date as of today). And this code depends on the sdk hence I didn't want to take the hassel upgrading the Azure DevOps extension SDK to the latest node etc.. 

To avoid this, try to run the sample from here (following the get-started docs) : https://developer.microsoft.com/en-us/azure-devops/develop/extensions

If you can run the samples on your box, this folder extension should work too.

**Comment by xdie** [comment]
Thanks  MoimHossain
